main(int argc, char* argv) {
    int c = 1 + 2;
    int p;
    int x = 1;
    int y = 1;
    char a = 'a';
    char b = 'b';
    string s = argv[1];
    string s1 = "coucou2";
    string s3;
    p = 3;
    s = s + "HELLO";
    s3 = s1+"coucou";
    string s2 = s1 + s;
    print(s2);
    print(s3);
    int[] tableau = {1, 2, 3, 4, 5};
    tableau[2] = 13;
    x = tableau[2];
    print(x);
    int z = len(tableau);
    print(z);
    int[] tableau2 = {{1, 2}, {3, 4}, {5, 6}};
    int[] extrait = tableau2[1];
    int size = len(tableau2[0]);
    print(size);
    print(len(extrait));
    y = tableau[1];
    print(tableau2[1][0]);
    print(tableau2[1][1]);
    return (y);
}